version: "3"
services:
  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
  good-deeds-bff:
    image: good-deeds-bff:0.1
    build: ./good-deeds-bff
    env_file:
    - ./good-deeds-bff/docker.env
    depends_on:
    - good-deeds-api
    ports:
      - '3001:3001'
  good-deeds-api:
    image: good-deeds-api:0.1
    build: ./good-deeds-api
    env_file:
    - ./good-deeds-api/docker.env
    ports:
    - 3000:3000
    depends_on:
    - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'