services:
  proxy:
    image: nginx:latest
    volumes:
      - hostPath: ./nginx.conf
        containerPath: /etc/nginx/nginx.conf
    ports:
      - 8080:80
  good-deeds-bff:
    image: good-deeds-bff:0.1
    build:
      context: ./good-deeds-bff
    environment:
      - RENDER_SERVICE_NAME=good-deeds-bff
    envVars:
      - key: MONGO_URL
        fromService:
          type: database
          name: mongo
          property: connectionString
    ports:
      - 3001:3001
  good-deeds-api:
    image: good-deeds-api:0.1
    build:
      context: ./good-deeds-api
    environment:
      - RENDER_SERVICE_NAME=good-deeds-api
    envVars:
      - key: MONGO_URL
        fromService:
          type: database
          name: mongo
          property: connectionString
    ports:
      - 3000:3000
    dependsOn:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
